//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangout.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/filter", ReplyAction="http://tempuri.org/IService1/filterResponse")]
        string filter(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/filter", ReplyAction="http://tempuri.org/IService1/filterResponse")]
        System.Threading.Tasks.Task<string> filterAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stemString", ReplyAction="http://tempuri.org/IService1/stemStringResponse")]
        string stemString(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stemString", ReplyAction="http://tempuri.org/IService1/stemStringResponse")]
        System.Threading.Tasks.Task<string> stemStringAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Hangout.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Hangout.ServiceReference2.IService1>, Hangout.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string filter(string s) {
            return base.Channel.filter(s);
        }
        
        public System.Threading.Tasks.Task<string> filterAsync(string s) {
            return base.Channel.filterAsync(s);
        }
        
        public string stemString(string s) {
            return base.Channel.stemString(s);
        }
        
        public System.Threading.Tasks.Task<string> stemStringAsync(string s) {
            return base.Channel.stemStringAsync(s);
        }
    }
}
